spring:
  application:
    name: ticket-booking
  datasource:
    url: jdbc:postgresql://localhost:5434/ticket_booking
    username: booking
    password: booking
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html
